<?php

include_once(BASE . '/application/Model/Model.php');
include_once(BASE . '/application/View/View.php');

class Controller_Register extends Model_Register
{

    private $Model;
    private $View;

    protected function install()
    {
        parent::install(); // TODO: Change the autogenerated stub
    }

    protected function uninstall()
    {
        parent::uninstall(); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        // Carrega o Model e View
        $this->Model = new Model_Register();
        $this->View = new View_Register();

        // Exporta Cadastros Registrados
        add_action('wp_ajax_ExportMysqlToCSV', array($this->Model, 'ExportMysqlToCSV'));

        // Cria novo usuário
        add_action('wp_ajax_create_new_user', array($this->Model, 'create_new_user'));
        add_action('wp_ajax_nopriv_create_new_user', array($this->Model, 'create_new_user'));

        // Mensagem de Alerta
        add_action('wp_head', array($this->Model, 'msg_alert'));

        // Menu Admin (Exportação XML)
        # add_action('admin_menu', array($this, 'options_menu_admin'));

        // Shortcodes
        add_shortcode('form_register', array($this, 'register'));
    }

    // Menu Admin
    public function options_menu_admin()
    {
        add_menu_page(
            'Exportar XML',
            'Exportar XML',
            'export_xml',
            'export_xml',
            array($this, 'get_options_menu_admin'),
            'dashicons-yes'
        );
    }

    // Captura Menu Admin
    public function get_options_menu_admin()
    {
        echo $this->View->render('form/options_menu_admin');
    }

    // Formulário de Registro
    public function register()
    {
        return $this->View->render('form/register');
    }

}