<?php

/**
 * Plugin Name: Módulo Cadastro (Register_User)
 * Plugin URI: https://www.facebook.com/tao.pires
 * Description: Módulo de Registro de Usuários
 * Version: 1.0
 * Author: Tiago Pires
 * Author URI: https://www.facebook.com/tao.pires
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

define('BASE', dirname(__FILE__));

require 'application/Controller/Controller.php';

class Register_Associate extends Controller_Register
{

    public function __construct()
    {
        parent::__construct();
    }

    public function install()
    {
        parent::install(); // TODO: Change the autogenerated stub
    }

    public function uninstall()
    {
        parent::uninstall(); // TODO: Change the autogenerated stub
    }

}

$register_associate = new Register_Associate();

// Chama Métode Instalação
register_activation_hook(dirname(__FILE__) . DIRECTORY_SEPARATOR . basename(__FILE__), array($register_associate, 'install'));
// Chama Métode Desinstalação
register_deactivation_hook(dirname(__FILE__) . DIRECTORY_SEPARATOR . basename(__FILE__), array($register_associate, 'uninstall'));